import type { NextPage } from "next";
import Head from "next/head";
import HomeContent from "../components/homepage/HomeContent";


const Home: NextPage = () => {
  return (
    <>
      <div className="min-h-screen">
        <Head>
          <title>Mads Rosenlund Nissen</title>
          <meta name="description" content="Generated by create-t3-app" />
          <link rel="icon" href="/favicon.png" />
        </Head>
        <HomeContent/>
      </div>
    </>
  );
};

export default Home;
